spring.application.name=clinic
spring.datasource.url=jdbc:postgresql://localhost:5432/Clinic
spring.datasource.username=root
spring.datasource.password=14159265
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=mySecretKey123!@#
jwt.expiration=86400000
